# Generated by Django 3.2 on 2022-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='description',
        ),
        migrations.AddField(
            model_name='company_profile',
            name='employee_strength',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
