# Generated by Django 3.2 on 2022-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0003_auto_20220410_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='employee_strength',
            field=models.IntegerField(default=0),
        ),
    ]
