# Generated by Django 3.2 on 2022-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0004_alter_company_profile_employee_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
