# Generated by Django 3.2 on 2022-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_auto_20220411_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
