# Generated by Django 3.2 on 2022-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0007_auto_20220412_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_user',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
