# Generated by Django 3.2 on 2022-04-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0010_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='seeker_name',
        ),
    ]
