# Generated by Django 3.2 on 2022-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0011_auto_20220414_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='saved_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
