# Generated by Django 3.2 on 2022-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0014_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='about_us',
            field=models.TextField(default='No bio....', max_length=2000),
        ),
    ]
