# Generated by Django 3.2 on 2022-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0017_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Selected', 'SELECTED'), ('Rejected', 'REJECTED'), {'INTERVIEW', 'Interview'}], default='Active', max_length=15),
        ),
    ]
