# Generated by Django 3.2 on 2022-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0018_auto_20220415_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
