# Generated by Django 4.0.3 on 2022-03-20 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('S', 'Prefer not to say')], default='S', max_length=1)),
                ('dob', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('U', 'User'), ('C', 'Company')], default='U', max_length=1)),
                ('about_us', models.CharField(default='No bio....', max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('picture', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'sent'), ('A', 'Accepted')], max_length=1)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=250)),
                ('Proficiency', models.CharField(choices=[('L1', 'Elementary proficiency0'), ('L2', 'Limited working proficiency'), ('L3', 'Professional working proficiency'), ('L4', 'Full professional proficiency'), ('L5', 'Native or bilingual proficiency')], max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('employement_type', models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time'), ('S', 'Self-employed'), ('F', 'Freelance'), ('I', 'Internship')], max_length=1)),
                ('company_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('is_current', models.BooleanField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=2500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('degree', models.CharField(blank=True, max_length=250)),
                ('field', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField(blank=True)),
                ('end_date_exp', models.DateField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(max_length=2500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('issuer', models.CharField(blank=True, max_length=250)),
                ('issue_date', models.DateField(blank=True)),
                ('description', models.CharField(max_length=2500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
