# Generated by Django 4.0.3 on 2022-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_end_date_exp_education_end_date_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Accepted', 'Accepted')], max_length=8),
        ),
    ]
