# Generated by Django 4.0.3 on 2022-03-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_address_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='profile',
            new_name='profileID',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='profile',
            new_name='profileID',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='profile',
            new_name='profileID',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='profile',
            new_name='profileID',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='profile',
            new_name='profileID',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='profile',
            new_name='profileID',
        ),
    ]
