# Generated by Django 4.0.3 on 2022-03-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_alter_experience_employement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='Proficiency',
        ),
        migrations.AddField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('Elementary-proficiency', 'Elementary proficiency'), ('Limited-working-proficiency', 'Limited working proficiency'), ('Professional-working-proficiency', 'Professional working proficiency'), ('Full-professional-proficiency', 'Full professional proficiency'), ('Native-or-bilingual-proficiency', 'Native or bilingual proficiency')], default='Elementary-proficiency', max_length=40),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('mentor', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('Work-in-Progress', 'Work in Progress'), ('Coming-soon', 'Coming soon'), ('Done', 'Done')], max_length=20)),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
