# Generated by Django 4.0.3 on 2022-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_score_skills_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
