# Generated by Django 3.2 on 2022-04-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_experience_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
    ]
