# Generated by Django 3.2 on 2022-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_experience_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Full-time', max_length=15),
        ),
    ]
