# Generated by Django 3.2 on 2022-04-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_experience_employement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
