# Generated by Django 3.2 on 2022-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_remove_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date_expected',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
