# Generated by Django 3.2 on 2022-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
